cc_library(
  name = "all",
  deps = [
    ":get_most_errors",
    ":get_most_queries",
    ":get_most_shutdowns",
    ":get_service_errors",
    ":get_service_number",
    ":get_service_shutdowns",
    ":get_service_traffic",
    ":get_services",
  ],
)

cc_binary(
  name = "get_most_errors",
  srcs = [
    "get_most_errors.cc",
  ],
  copts = [
    "-std=c++17",
    "-lglog",
    "-lpthread",
    "-lgflags",
  ],
  linkopts = [
    "-lglog",
    "-pthread",
    "-lgflags",
  ],
  deps = [
    "//blade:framework",
    "//blmesh:noncopyable",
    "//blmesh:rw_lock",
  ],
)

cc_binary(
  name = "get_most_queries",
  srcs = [
    "get_most_queries.cc",
  ],
  copts = [
    "-std=c++17",
    "-lglog",
    "-lpthread",
    "-lgflags",
  ],
  linkopts = [
    "-lglog",
    "-pthread",
    "-lgflags",
  ],
  deps = [
    "//blade:framework",
    "//blmesh:noncopyable",
    "//blmesh:rw_lock",
  ],
)

cc_binary(
  name = "get_most_shutdowns",
  srcs = [
    "get_most_shutdowns.cc",
  ],
  copts = [
    "-std=c++17",
    "-lglog",
    "-lpthread",
    "-lgflags",
  ],
  linkopts = [
    "-lglog",
    "-pthread",
    "-lgflags",
  ],
  deps = [
    "//blade:framework",
    "//blmesh:noncopyable",
    "//blmesh:rw_lock",
  ],
)

cc_binary(
  name = "get_service_errors",
  srcs = [
    "get_service_errors.cc",
  ],
  copts = [
    "-std=c++17",
    "-lglog",
    "-lpthread",
    "-lgflags",
  ],
  linkopts = [
    "-lglog",
    "-pthread",
    "-lgflags",
  ],
  deps = [
    "//blade:framework",
    "//blmesh:noncopyable",
    "//blmesh:rw_lock",
  ],
)

cc_binary(
  name = "get_service_number",
  srcs = [
    "get_service_number.cc",
  ],
  copts = [
    "-std=c++17",
    "-lglog",
    "-lpthread",
    "-lgflags",
  ],
  linkopts = [
    "-lglog",
    "-pthread",
    "-lgflags",
  ],
  deps = [
    "//blade:framework",
    "//blmesh:noncopyable",
    "//blmesh:rw_lock",
  ],
)

cc_binary(
  name = "get_service_queries",
  srcs = [
    "get_service_queries.cc",
  ],
  copts = [
    "-std=c++17",
    "-lglog",
    "-lpthread",
    "-lgflags",
  ],
  linkopts = [
    "-lglog",
    "-pthread",
    "-lgflags",
  ],
  deps = [
    "//blade:framework",
    "//blmesh:noncopyable",
    "//blmesh:rw_lock",
  ],
)

cc_binary(
  name = "get_service_shutdowns",
  srcs = [
    "get_service_shutdowns.cc",
  ],
  copts = [
    "-std=c++17",
    "-lglog",
    "-lpthread",
    "-lgflags",
  ],
  linkopts = [
    "-lglog",
    "-pthread",
    "-lgflags",
  ],
  deps = [
    "//blade:framework",
    "//blmesh:noncopyable",
    "//blmesh:rw_lock",
  ],
)

cc_binary(
  name = "get_service_traffic",
  srcs = [
    "get_service_traffic.cc",
  ],
  copts = [
    "-std=c++17",
    "-lglog",
    "-lpthread",
    "-lgflags",
  ],
  linkopts = [
    "-lglog",
    "-pthread",
    "-lgflags",
  ],
  deps = [
    "//blade:framework",
    "//blmesh:noncopyable",
    "//blmesh:rw_lock",
  ],
)

cc_binary(
  name = "get_services",
  srcs = [
    "get_services.cc",
  ],
  copts = [
    "-std=c++17",
    "-lglog",
    "-lpthread",
    "-lgflags",
  ],
  linkopts = [
    "-lglog",
    "-pthread",
    "-lgflags",
  ],
  deps = [
    "//blade:framework",
    "//blmesh:noncopyable",
    "//blmesh:rw_lock",
  ],
)
